---
title: "Data Wrangling"
author: "Taryn O'Connor"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringdist)
library(rstanarm)
library(tidymodels)
library(gtsummary)
library(gt)


```

```{r reading data sets, message = FALSE, error = F}

# After downloading each dataset from the FEC and MIT Election Lab, I used
# read_csv to save each set into its own object.

sen_1980 <- read_csv("raw_data/senate_1980.csv")
sen_1982 <- read_csv("raw_data/senate_1982.csv")
sen_1984 <- read_csv("raw_data/senate_1984.csv")
sen_1986 <- read_csv("raw_data/senate_1986.csv")
sen_1988 <- read_csv("raw_data/senate_1988.csv")
sen_1990 <- read_csv("raw_data/senate_1990.csv")
sen_1992 <- read_csv("raw_data/senate_1992.csv")
sen_1994 <- read_csv("raw_data/senate_1994.csv")
sen_1996 <- read_csv("raw_data/senate_1996.csv")
sen_1998 <- read_csv("raw_data/senate_1998.csv")
sen_2000 <- read_csv("raw_data/senate_2000.csv")
sen_2002 <- read_csv("raw_data/senate_2002.csv")
sen_2004 <- read_csv("raw_data/senate_2004.csv")
sen_2006 <- read_csv("raw_data/senate_2006.csv")
sen_2008 <- read_csv("raw_data/senate_2008.csv")
sen_2010 <- read_csv("raw_data/senate_2010.csv")
sen_2012 <- read_csv("raw_data/senate_2012.csv")
sen_2014 <- read_csv("raw_data/senate_2014.csv")
sen_2016 <- read_csv("raw_data/senate_2016.csv")
sen_2018 <- read_csv("raw_data/senate_2018.csv")
sen_2020 <- read_csv("raw_data/senate_2020.csv")
mit_data <- read_csv("raw_data/1976-2018-senate.csv") %>% 
  arrange(desc(year))

# Although the MIT data contained data from 1976-2018, I only downloaded data 
# from 1980-2018 from the FEC due to the availability of campaign finance data

```

```{r fec and vote_totals, message = FALSE}
# I then used rbind to combine all of the FEC datasets for each election year 
# into one singular FEC dataset. 

fec <- rbind(sen_1980, sen_1982, sen_1984, 
             sen_1986, sen_1988, sen_1990, 
             sen_1992, sen_1994, sen_1996, 
             sen_1998, sen_2000, sen_2002, 
             sen_2004, sen_2006, sen_2008, 
             sen_2010, sen_2012, sen_2014, 
             sen_2016, sen_2018, sen_2020) %>% 
  
# The datasets contained info that wasn't relevant to my project, such as filing 
# dates and addresses, so I selected only the columns that were necessary
  
  select(name, 
         office, 
         party, 
         state, 
         candidate_election_year, 
         incumbent_challenge_full,
         receipts, disbursements, 
         cash_on_hand_end_period, 
         candidate_id) %>% 
  
# In order to use a function later on to combine the campaign finance and election
# results datasets, I had to clean up the sames of the FEC dataset, which were 
# in a LASTNAME, FIRSTNAME format. To do this, I separated each name into 
# separate columns, rejoined the first and last name columns in order, and
# reformatted the names so that the first letter would be capitalized and the names
# would be as close as possible to the names in the MIT Election Lab dataset.
  
  separate(name, into = c("last", "first_middle"), sep = ", ") %>% 
  separate(first_middle, into = c("first", "middle"), sep = " ") %>% 
  unite(full_name, "first", "last", sep = " ") %>% 
  select(-middle) %>% 
  mutate(full_name = tolower(full_name)) %>% 
  mutate(full_name = str_to_title(full_name)) %>% 
  
# To begin narrowing down the data to exclude candidates eliminated in primaries,
# I filtered the data to include candidates who received contributions
  
  filter(receipts > 0.00) %>% 
  
# To finish, I renamed the candidate_election_year column to year in order to 
# join the two datasets later on.
  
  mutate(year = candidate_election_year)

# With the MIT data, I first filtered it so that it only contained general 
# election results from 1980-2018.

vote_totals <- mit_data %>% 
  filter(year >= 1980) %>% 
  filter(stage == "gen") %>% 
  
# I then calculated the percent of votes each candidate received by grouping by
# year, the type of election, state, and candidate name. Party was excluded since
# candidates can run as the nominee of multiple parties
  
  group_by(year, state_po, special, candidate) %>% 
  mutate(cand_totalvotes = sum(candidatevotes)) %>% 
  mutate(vote_percentage = cand_totalvotes/totalvotes * 100) %>%
  
# I then eliminated any write-in entries in the data, as they were not relevant 
# to my analysis.
  
  filter(writein == "FALSE") %>% 
  
# I then selected only the columns that were relevant to my analysis.
  
  select(year, 
         state, 
         state_po, 
         special, 
         candidate, 
         cand_totalvotes, 
         vote_percentage) %>% 
  
# Since there were some duplicates due to candidates running under multiple 
# parties, I used unique() to eliminate duplicates. 
  
  unique() %>% 
  
# To finish, I selected only candidates who received 10%+ of votes. This was done 
# to eliminate candidates who never filed with the FEC (and thus interfered with 
# my ability to accurately match candidates to FEC filings)
  
  filter(vote_percentage >= 10) %>% 
  arrange(desc(year))

```


```{r stringdist function}
# I created the following function to match candidates from the MIT data to their
# FEC filings

name <- function(candidate, year, state_po){
  fec %>% 
    
# First, it filtered down the FEC data to include only elections from the year 
# and state of the candidate being matched.
    
    filter(state == state_po) %>% 
    filter(year == year) %>% 
    
# It then mapped the name of the remaining candidates to a stringdist function, 
# where it would be compared with the name of the candidate being matched. The
# stringdist function would return a distance for each potential match, with the
# lowest value corresponding to the closest match. 
    
    mutate(distance = map_dbl(full_name, ~ stringdist(., candidate))) %>% 
    
# The function then selected the candidate with the lowest distance (closest
# match), and pulled the FEC candidate ID of the match
    
    slice(which.min(distance)) %>% 
    pull(candidate_id)
}

```

```{r fec_id_vote}
# I then mapped this function to every candidate in the MIT data, and created
# a column that contained the FEC ID match for each candidate.

fec_id_vote <- vote_totals %>%
  mutate(candidate_id = pmap_chr(list(candidate = candidate, 
                                candidate_election_year = year, 
                                state_po = state_po),
                           .f = ~ name(candidate = ..1, 
                                       year = ..2, 
                                       state = ..3)))

```

```{r joining}
# I then joined the new dataset to the fec dataset by year and candidate id so that
# each race would also contain data for the amount of money raised and spent by 
# each campaign.

contribution_votes <- left_join(fec_id_vote, fec, 
                                by = c("candidate_id", "year")) %>% 
  
# In order to build my models, I changed the year column to be characters rather
# than numbers
  
  mutate(year = as.character(year)) %>% 
  
# I also changed any "DFL" entries in the party column to "DEM" since DFL refers
# to the Democratic Farmer-Labor Party of Minnesota, which is an affiliate of the
# Democratic Party.
  
  mutate(party = ifelse(party == "DFL", "DEM", party)) %>% 
  
# I also changed disbursements to be represented in thousands of dollars, in order
# to make any graphs cleaner.
  
  mutate(disbursements = disbursements/1000) %>% 

# Since the FEC data had NA's for many challengers in the incumbent_challenge_full
# column for elections from 1980 - 1986, I replaced these NA's with "Challenger"
    
  replace_na(list(incumbent_challenge_full = "Challenger"))

```

```{r linear model of disbursements x vote percentage}
# First, I made a new dataset called votes, which only contained the year, 
# disbursements and vote percentage (as these were the only relevant columns)

votes <- contribution_votes %>% 
  ungroup() %>% 
  select(year, disbursements, vote_percentage) %>% 
  
# I also dropped any columns containing NA values (mostly candidates who filed 
# for one election but not another)  
  
  drop_na()

votes_split <- initial_split(votes, prop = .8)
votes_train <- training(votes_split)
votes_test <- training(votes_split)
votes_folds <- vfold_cv(votes_train, v = 10)

# In my app, there is an option to select a year, which is then filtered out of
# the object votes. An example will be made with the year set to 2018

votes_ex <- votes %>% 
  filter(year == 1998)

# To make my linear model, I first used stan_glm to find the relationship between
# disbursements and vote_percentage

model_votes <- stan_glm(data = votes_ex,
                        vote_percentage ~ disbursements,
                        family = gaussian(),
                        refresh = 0)

print(model_votes, digits = 4)

# I then used this model to generate a graph showing the linear relationship 
# with all of the data points for the given year. 

votes_ex %>% 
  ggplot(aes(x = disbursements, y = vote_percentage)) +
  geom_point() +
  geom_line(aes(y = fitted(model_votes)), color = "red") +
  theme_classic() +
  labs(title = "Relationship Between Campaign Expenditures and Percent of 
       Overall Vote")

# I also made a graph for a local regression, which shows a different trend
# than the linear model. This was achieved by inserting a formula with the method
# "loess", instead of using the stan_glm model. 

votes_ex %>% 
  ggplot(aes(x = disbursements, y = vote_percentage)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method = "loess", color = "red") +
  theme_classic() 

# I also wanted to show how the predictions of the linear model compared with 
# the actual vote percentages for each candidate:

# First, I split the data into testing and training sets, and a folds set for 
# metrics


votes_ex_split <- initial_split(votes_ex, prop = .8)
votes_ex_train <- training(votes_ex_split)
votes_ex_test <- training(votes_ex_split)
votes_ex_folds <- vfold_cv(votes_ex_train, v = 10)

# Then, I piped workflow() into a linear regression stan model, using the same
# formula as model_votes in the recipe

votes_wfl <- workflow() %>% 
  add_model(linear_reg() %>%
            set_engine("stan") %>%
            set_mode("regression")) %>% 
  add_recipe(recipe(vote_percentage ~  disbursements,
                    data = votes_ex_train) %>% 
             step_dummy(all_nominal())
             ) 

# I took the new_workflow, and fit it to the training set before predicting with
# the testing set. I then took the predictions and binded them to the original
# vote percentages and plotted them. 

votes_wfl %>% 
  fit(data = votes_ex_train) %>% 
  predict(new_data = votes_ex_test) %>% 
  bind_cols(votes_ex_train %>% select(vote_percentage)) %>% 
  ggplot(aes(x = vote_percentage, y = .pred)) +
    geom_point()

# I then ran metrics on the workflow by resampling with the folds dataset

votes_metrics <- votes_wfl %>% 
  fit_resamples(resamples = votes_ex_folds) %>% 
  collect_metrics()


votes_metrics %>% 
  rename("Metric" = .metric,
         "Mean" = mean,
         "Estimator" = .estimator,
         "Standard Error" = std_err) %>% 
  gt()
  
  
```

 
```{r incumbent model}
# I was also curious to see what other factors can play into the outcome of an 
# election, so I looked at how incumbents and challengers often performed over
# the years.

# To do this, I again used stan_glm, but with the formula now being
# vote_percentage ~ incumbent_challenge_full + year - 1

model_2 <- stan_glm(data = contribution_votes,
         vote_percentage ~ incumbent_challenge_full + year - 1,
         family = gaussian(),
         refresh = 0)

print(model_2, digits = 4)

# I then saved the results from the model as a tibble, and renamed each column
# to simplify their names, adding a 1980 column as well to be used later in 
# cleaning up the data for the models

model_2_data <- model_2 %>% 
  as_tibble() %>% 
  add_column(year1980 = 0) %>% 
  mutate(challenger = incumbent_challenge_fullChallenger,
         incumbent = incumbent_challenge_fullIncumbent,
         open_seat = `incumbent_challenge_fullOpen seat`,
         `1980` = year1980,
         `1982` = year1982,
         `1984` = year1984,
         `1986` = year1986,
         `1988` = year1988,
         `1990` = year1990,
         `1992` = year1992,
         `1994` = year1994,
         `1996` = year1996,
         `1998` = year1998,
         `2000` = year2000,
         `2002` = year2002,
         `2004` = year2004,
         `2006` = year2006,
         `2008` = year2008,
         `2010` = year2010,
         `2012` = year2012,
         `2014` = year2014,
         `2016` = year2016,
         `2018` = year2018) %>% 
  
# I then pivoted the columns and added the values to each year column to get a
# set of data points for each year
  
  pivot_longer(cols = challenger:open_seat,
               names_to = "candidate_status",
               values_to = "percent_vote") %>% 
  mutate(`1980` = `1980` + percent_vote,
         `1982` = `1982` + percent_vote,
         `1984` = `1984` + percent_vote,
         `1986` = `1986` + percent_vote,
         `1988` = `1988` + percent_vote,
         `1990` = `1990` + percent_vote,
         `1992` = `1992` + percent_vote,
         `1994` = `1994` + percent_vote,
         `1996` = `1996` + percent_vote,
         `1998` = `1998` + percent_vote,
         `2000` = `2000` + percent_vote,
         `2002` = `2002` + percent_vote,
         `2004` = `2004` + percent_vote,
         `2006` = `2006` + percent_vote,
         `2008` = `2008` + percent_vote,
         `2010` = `2010` + percent_vote,
         `2012` = `2012` + percent_vote,
         `2014` = `2014` + percent_vote,
         `2016` = `2016` + percent_vote,
         `2018` = `2018` + percent_vote) %>% 
  select(`1980`:percent_vote)
  
saveRDS(model_2_data, "model_2.RDS")

# I then plotted this data (again using 2018 example) such that the selection from
# the app would be plotted.

input <- 2018

model_2_data %>% 
  rename(year = as.character(input)) %>%
  ggplot(aes(x = year, y = after_stat(count/sum(count)), fill = candidate_status)) +
  geom_histogram(bins = 100,
                 alpha = .5,
                 position = "identity")


```

```{r incumbent/challenger/open_seat comparison}

# In order to determine if there is any difference in the models when broken
# down by type of candidate, I generated regressions for each type of candidate
# In my app, the year can be inputted, with the below being the input should
# 1980 be chosen.

# For each type of candidate, I made a dataset filtered to the year and type of
# candidate. I also used drop_na in order to plot the regressions later on

challenger <- contribution_votes %>% 
  filter(year == 1980) %>% 
  filter(incumbent_challenge_full == "Challenger") %>% 
  drop_na()

incumbent <- contribution_votes %>% 
  filter(year == 1980) %>% 
  filter(incumbent_challenge_full == "Incumbent") %>% 
  drop_na()

open_seat <- contribution_votes %>% 
  filter(year == 1982) %>% 
  filter(incumbent_challenge_full == "Open seat") %>% 
  drop_na()

# I then made models with each dataset that measured the effect of disbursements
# on vote_percentage

model_4 <- stan_glm(data = incumbent,
         vote_percentage ~ disbursements,
         family = gaussian(),
         refresh = 0)

model_5 <- stan_glm(data = challenger,
         vote_percentage ~ disbursements,
         family = gaussian(),
         refresh = 0)

model_6 <- stan_glm(data = open_seat,
         vote_percentage ~ disbursements,
         family = gaussian(),
         refresh = 0)

# I then took these models and plotted them on one graph

incumbent %>% 
  ggplot(aes(x = disbursements, 
             y = vote_percentage)) +
  
# I also included a scatter plot with campaigns being identified as incumbents,
# challengers, or open seats
  
  geom_point(aes(color = "blue")) +
  geom_line(aes(y = fitted(model_4), 
                color = "blue")) +
  geom_point(data = challenger, 
             aes(x = disbursements, 
                 y = vote_percentage, 
                 color = "red")) +
  geom_line(data = challenger, 
            aes(y = fitted(model_5),
                color = "red")) +
  geom_point(data = open_seat,
             aes(x = disbursements, 
                 y = vote_percentage,
                 color = "yellow")) +
  geom_line(data = open_seat, 
            aes(y = fitted(model_6), 
                color = "yellow")) +
  
# I then ordered and renamed the scale such that it matched the posterior 
# distribution that would be on the same tab
  
  scale_color_manual(breaks = c("red", "blue", "yellow"),
                     values = c("blue" = "blue", 
                               "yellow" = "#FFCC33",
                               "red" = "red"),
                     labels = c("Challenger", "Incumbent", "Open Seat")) +
  theme_classic()

# I opted not to put tables measuring the reliability, since there was often
# not enough data for an accurate measurement

```


```{r national partisan difference in spending}
# This graph shows the change in campaign expenditures over time for all 
# Democratic and Republican Senate races. 

contribution_votes %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(party == "DEM" | party == "REP") %>% 
  ggplot(aes(x = year, y = disbursements/1000, color = party)) + 
  
# I chose to have both a scatter plot and regression line to show overall trends,
# as well as outliers. 
  
  geom_point(alpha = .3) +
  geom_smooth(alpha = .6) +
  scale_color_manual(values = c("DEM" = "blue", "REP" = "red"), 
                     labels = c("Democrat", "Republican")) +
  labs(title = "Spending on Democratic and Republican Senate Campaigns,
       1980 - 2018",
       x = "Year",
       y = "Spendings (in Millions of Dollars)",
       color = "Party") +
  theme_bw() 
```

```{r spending margin for winners (by state)}

# I also wanted to look at how much candidates outspent each other. 

win_pre <- contribution_votes %>% 
  group_by(year, state_po, special) %>% 
  
# To do this, I found the candidate with the highest vote percentage and 
# identified them with TRUE in the new win column
  
  mutate(max = max(vote_percentage, na.rm = FALSE)) %>% 
  mutate(win = ifelse(vote_percentage == max, TRUE, FALSE)) 

# I then found how many major contenders were in each race and added it to the
# dataset with inner_join().

n_candidates <- win_pre %>% 
  group_by(year, state_po, special) %>% 
  tally()

win <- inner_join(win_pre, n_candidates, by = c("year", "state_po", "special"))



```


```{r state differences in expenditures}

# I wanted to include a plot where a comparison could be made of how much 
# winners outspent their opponent in each state (since a national comparison would
# be ineffective (ex. comparing a CA race to a WY race))

# Also since this was looking at the difference in races, in order to calculate this
# I narrowed it down to races with only 2 major contenders. 

plot_1 <- win %>% 
  filter(n == 2) %>% 
  arrange(year, state_po, special, desc(vote_percentage)) %>% 
  
# I also had to directly change the values for some candidates, as they didn't 
# file with the FEC, causing the function to match them to their opponent, which
# would return an inaccurate value of $0 for outspending. 
  
  mutate(disbursements = 
           ifelse(candidate == "Albert N. Gore, Jr.", 0, disbursements)) %>%
  mutate(disbursements = 
           ifelse(candidate == "Crystal Young", 0, disbursements)) %>%
  mutate(disbursements = 
           ifelse(candidate == "Shawn O'Hara", 0, disbursements)) %>%
  mutate(disbursements = 
           ifelse(candidate == "Charlie A. Matulka", 0, disbursements)) %>%
  mutate(disbursements = 
           ifelse(candidate == "Guy MacDonald", 0, disbursements)) %>%
  
# I then calculated the difference in expenditures, and filtered only the winners,
# as the difference equalled how much the winner outspent their opponent
  
  mutate(diff = disbursements[[1]] - disbursements[[2]]) %>% 
  filter(win == "TRUE") %>% 
  drop_na()

# I then made a plot where one can choose a state and it shows the outspending for
# each Senate campaign with 2 major contenders (example below with Massachusetts)

plot_1 %>% 
  filter(state.x == "Massachusetts") %>% 
  ggplot(aes(x = year, y = diff, color = party)) +
  geom_point(size = 5) +
  scale_color_manual(breaks = c("DEM", "REP", "IND"),
                     values = c("DEM" = "darkblue", "REP" = "darkred", "IND" = "darkgreen"), 
                     labels = c("Democrat", "Republican", "Independent")) +
  labs(title = "",
       subtitle = "How much winners outspent their opponents in races with two major contenders",
       x = "Election Year",
       y = "Spending Margin (in Millions of Dollars)",
       color = "Party") +
  scale_x_discrete(breaks = c(1980, 1982, 1984, 1986, 1988, 1990, 
                                          1992, 1994, 1996, 1998, 2000, 2002, 
                                          2004, 2006, 2008, 2010, 2012, 2014, 
                                          2016, 2018)) +
  theme_bw() +
  
# For all my plots in my app, I had to change the font size to make it easier 
# to view in the app.
  
  scale_y_continuous(labels = scales::comma) +
  theme(text = element_text(size = 15), 
        axis.text = element_text(size = 12), 
        axis.title = element_text(size = 20,face = "bold"))

```


```{r shiny app data}

# For my app, I saved each of my datasets as .RDS files to load in the app

saveRDS(contribution_votes, "contribution_votes.RDS")
saveRDS(model_2_data, "model_2.RDS")
saveRDS(plot_1, "plot_1.RDS")
saveRDS(votes, "votes.RDS")
saveRDS(votes_split, "votes_split.RDS")
saveRDS(votes_train, "votes_train.RDS")
saveRDS(votes_test , "votes_test.RDS")
```

